//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision_Pharmacy.Code {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_En {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_En() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vision_Pharmacy.Code.Resources_En", typeof(Resources_En).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string AddButton_User {
            get {
                return ResourceManager.GetString("AddButton_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add operation completed successfully.
        /// </summary>
        internal static string AddNotificationText {
            get {
                return ResourceManager.GetString("AddNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to do this? Data cannot be recovered..
        /// </summary>
        internal static string DeleteActionCaption {
            get {
                return ResourceManager.GetString("DeleteActionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete action.
        /// </summary>
        internal static string DeleteActionText {
            get {
                return ResourceManager.GetString("DeleteActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete operation completed successfully..
        /// </summary>
        internal static string DeleteNotificationText {
            get {
                return ResourceManager.GetString("DeleteNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete action..
        /// </summary>
        internal static string DeleteOutComeText {
            get {
                return ResourceManager.GetString("DeleteOutComeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This deletion operation does not affect existing items. If you are also removing items, you must edit them and then delete them..
        /// </summary>
        internal static string DeletOutComeCaption {
            get {
                return ResourceManager.GetString("DeletOutComeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some data, such as the ID, should not be repeated. Make sure to change it and try again..
        /// </summary>
        internal static string DuplicateDataCaption {
            get {
                return ResourceManager.GetString("DuplicateDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate data..
        /// </summary>
        internal static string DuplicateDataText {
            get {
                return ResourceManager.GetString("DuplicateDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit operation successful..
        /// </summary>
        internal static string EditNotificationText {
            get {
                return ResourceManager.GetString("EditNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No data. Use the buttons above to perform data operations..
        /// </summary>
        internal static string EmptyDataText {
            get {
                return ResourceManager.GetString("EmptyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The data grid is empty. Make sure you have selected a row to complete the operation..
        /// </summary>
        internal static string EmptyGridViewCaption {
            get {
                return ResourceManager.GetString("EmptyGridViewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your data grid is empty..
        /// </summary>
        internal static string EmptyGridViewText {
            get {
                return ResourceManager.GetString("EmptyGridViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fields marked with an asterisk (*) are required. Make sure you enter it correctly and try again..
        /// </summary>
        internal static string FiledsEmptyCaption {
            get {
                return ResourceManager.GetString("FiledsEmptyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some fields are required..
        /// </summary>
        internal static string FiledsEmptyText {
            get {
                return ResourceManager.GetString("FiledsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New User Form.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warehouse..
        /// </summary>
        internal static string GeneralText {
            get {
                return ResourceManager.GetString("GeneralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a valid value..
        /// </summary>
        internal static string InvalidInputCaption {
            get {
                return ResourceManager.GetString("InvalidInputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input error..
        /// </summary>
        internal static string InvalidIputText {
            get {
                return ResourceManager.GetString("InvalidIputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Iraq Vision Pharmacy Management Program
        ///© 2025 - All Rights Reserved
        ///.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string labelControl1 {
            get {
                return ResourceManager.GetString("labelControl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name User.
        /// </summary>
        internal static string labelControl2 {
            get {
                return ResourceManager.GetString("labelControl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome.
        /// </summary>
        internal static string labelControl3 {
            get {
                return ResourceManager.GetString("labelControl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New User.
        /// </summary>
        internal static string LabelNewUser {
            get {
                return ResourceManager.GetString("LabelNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authority.
        /// </summary>
        internal static string LabelRole {
            get {
                return ResourceManager.GetString("LabelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        internal static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Iraq Vision Pharmacy Management Program.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee Attendance and Absence Recording.
        /// </summary>
        internal static string lblTitleAttend {
            get {
                return ResourceManager.GetString("lblTitleAttend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer List.
        /// </summary>
        internal static string lblTitleCustom {
            get {
                return ResourceManager.GetString("lblTitleCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee List.
        /// </summary>
        internal static string lblTitleEmp {
            get {
                return ResourceManager.GetString("lblTitleEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expired Medication List.
        /// </summary>
        internal static string lblTitleExpired {
            get {
                return ResourceManager.GetString("lblTitleExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Medicine List.
        /// </summary>
        internal static string lblTitleMedicat {
            get {
                return ResourceManager.GetString("lblTitleMedicat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee Payroll List.
        /// </summary>
        internal static string lblTitlePay {
            get {
                return ResourceManager.GetString("lblTitlePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purchase List.
        /// </summary>
        internal static string lblTitlePurchase {
            get {
                return ResourceManager.GetString("lblTitlePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The item will be moved to the damaged section..
        /// </summary>
        internal static string OnDamgeCaption {
            get {
                return ResourceManager.GetString("OnDamgeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action Destroy.
        /// </summary>
        internal static string OnDamgeText {
            get {
                return ResourceManager.GetString("OnDamgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The item will be moved to the Out of Conscince section..
        /// </summary>
        internal static string OutOfConscinceCaption {
            get {
                return ResourceManager.GetString("OutOfConscinceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move Out of Conscience..
        /// </summary>
        internal static string OutOfConscinceText {
            get {
                return ResourceManager.GetString("OutOfConscinceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print.
        /// </summary>
        internal static string PrintButton_User {
            get {
                return ResourceManager.GetString("PrintButton_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The added quantity cannot be greater than the available quantity. Check the quantity for the current item and make sure it is greater than or equal to zero, then try again..
        /// </summary>
        internal static string QuantityMaterialCaption {
            get {
                return ResourceManager.GetString("QuantityMaterialCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid quantity..
        /// </summary>
        internal static string QuantityMaterialText {
            get {
                return ResourceManager.GetString("QuantityMaterialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrator.
        /// </summary>
        internal static string RoleAdmin {
            get {
                return ResourceManager.GetString("RoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        internal static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It appears that you did not save and have added data. We&apos;ll keep it, and you can refer to it in the next add operation..
        /// </summary>
        internal static string SavedDataCaption {
            get {
                return ResourceManager.GetString("SavedDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remember!.
        /// </summary>
        internal static string SavedDataText {
            get {
                return ResourceManager.GetString("SavedDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It seems you&apos;re having a problem with this operation. This could be due to several reasons, including a connection between this data and other data that needs to be deleted first. It could also be due to incorrect server installation, incorrect access permissions, an uninstalled database, or a database connection error. You can modify the connection text in the system settings, or you can contact the system administrator to resolve the issue..
        /// </summary>
        internal static string ServerConnectionCaption {
            get {
                return ResourceManager.GetString("ServerConnectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database connection error..
        /// </summary>
        internal static string ServerConnectionText {
            get {
                return ResourceManager.GetString("ServerConnectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This action will completely delete the material from here and from other materials..
        /// </summary>
        internal static string ShowDeleteMaterialCaption {
            get {
                return ResourceManager.GetString("ShowDeleteMaterialCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This action will completely delete the material, and other materials will be affected..
        /// </summary>
        internal static string ShowMoveDamgeCaption {
            get {
                return ResourceManager.GetString("ShowMoveDamgeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Material..
        /// </summary>
        internal static string ShowMoveDamgeText {
            get {
                return ResourceManager.GetString("ShowMoveDamgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For sensitivity, you must select &quot;Complete.&quot; The line. If you want to delete the entire data, you can press CTRL+A..
        /// </summary>
        internal static string ShowRowsCaption {
            get {
                return ResourceManager.GetString("ShowRowsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Make sure to select the entire line to delete..
        /// </summary>
        internal static string ShowRowText {
            get {
                return ResourceManager.GetString("ShowRowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string SwitchLang {
            get {
                return ResourceManager.GetString("SwitchLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purchase List.
        /// </summary>
        internal static string TitlePurchase {
            get {
                return ResourceManager.GetString("TitlePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User List.
        /// </summary>
        internal static string TitleUser {
            get {
                return ResourceManager.GetString("TitleUser", resourceCulture);
            }
        }
    }
}
